kind: pipeline
type: aws
name: default

instance:
# ubuntu 18.04 t1-micro ohio
  ami: ami-051197ce9cbb023ea 
  use_pool: true
  type: t2.nano
  network:
    security_groups:
      - sg-0f5aaeb48d35162a4 
      
steps:
- name: display go version
  image: golang
  pull: if-not-exists
  commands:
  - go version
