kind: pipeline
type: docker
name: build
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 10

---
kind: pipeline
type: docker
name: test
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "fail."
  - name: fail
    image: alpine:latest
    commands:
    - exit 1
--- 

kind: pipeline
type: docker
name: tools
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "This is a fast pipeline with success."

---
kind: pipeline
type: docker
name: deploy
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "This is a dummy fast step."
depends_on:
  - build

---
kind: pipeline
type: docker
name: perf
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "This is a dummy fast step."
depends_on:
  -  build
